server:
    port: 8081

spring:
    security:
        oauth2:
            client:
                registration:
                    keycloak:
                        clientId: oauth2-client-app
                        clientSecret: zakIo7yUuNuihdDBRibSDY3hdYtkN9x2
                        clientName: oauth2-client-app
                        authorizationGrantType: authorization_code
                        scope: openid,email,profile
                        clientAuthenticationMethod: client_secret_basic
                        redirectUri: http://localhost:8081/login/oauth2/code/keycloak

                provider:
                    keycloak:
                        issuerUri: https://sdevtest.genians.kr:30004/realms/Oauth2
                        authorizationUri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/auth
                        tokenUri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/token
                        userInfoUri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/userinfo
                        jwkSetUri: https://sdevtest.genians.kr:30004/realms/Oauth2/protocol/openid-connect/certs
                        userNameAttribute: preferred_username